// build-ts.mjs — esbuild the authored TypeScript into the runtime .mjs that wrangler +
// worker-build consume, BEFORE worker-build runs.
//
// Two outputs, each preserving the EXACT module exports/shape the consumers expect:
//
//   1. src/kernel-glue.ts -> src/kernel-glue.mjs
//      The path `#[wasm_bindgen(module = "/src/kernel-glue.mjs")]` in lib.rs reads + worker-build
//      copies into its wasm-bindgen snippet dir. Must export: newGlueKernel, getEngineHash,
//      newMutex (and the GlueKernel/Mutex method shape lib.rs binds). repl-transform.ts is
//      INLINED here (bundle:true) so the single .mjs has no sibling import (which would not
//      resolve in the snippet dir).
//
//   2. entry.ts -> entry.mjs
//      The wrangler `main`. The wrangler-special imports (engine.wasm CompiledWasm,
//      stdlib.bundle.txt Text, build/worker/shim.mjs) are kept EXTERNAL so wrangler/worker-build
//      resolve them at the wrangler-bundle step. engine-hash.js is ALSO external — it is
//      regenerated by engine-hash.mjs AFTER this step, so inlining it would freeze a stale hash;
//      wrangler bundles the FRESH file at deploy. stdlib-meta is inlined (pure data, stable).
//
// Determinism: format=esm, no minify, target matches tsconfig (ES2022). Behavior identical.

import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

const COMMON = {
  bundle: true,
  format: "esm",
  target: "es2022",
  platform: "neutral",
  minify: false,
  sourcemap: false,
  legalComments: "none",
};

// 1. kernel-glue: self-contained single-file ESM (repl-transform inlined).
await build({
  ...COMMON,
  entryPoints: [resolve(root, "src/kernel-glue.ts")],
  outfile: resolve(root, "src/kernel-glue.mjs"),
});
console.log("[build-ts] src/kernel-glue.ts -> src/kernel-glue.mjs");

// 2. entry: keep the wrangler-special imports external (resolved by wrangler rules / worker-build).
await build({
  ...COMMON,
  entryPoints: [resolve(root, "entry.ts")],
  outfile: resolve(root, "entry.mjs"),
  external: ["*.wasm", "*.txt", "./build/worker/shim.mjs", "./src/engine-hash.js"],
});
console.log("[build-ts] entry.ts -> entry.mjs");
