// build-ts.mjs — esbuild the authored TypeScript into the runtime .mjs that wrangler +
// worker-build consume, BEFORE worker-build runs.
//
// Two outputs, each preserving the EXACT module exports/shape the consumers expect:
//
//   1. src/kernel-glue.ts -> src/kernel-glue.mjs
//      The path `#[wasm_bindgen(module = "/src/kernel-glue.mjs")]` in lib.rs reads + worker-build
//      copies into its wasm-bindgen snippet dir. Must export: newGlueKernel, getEngineHash,
//      newMutex (and the GlueKernel/Mutex method shape lib.rs binds). repl-transform.ts is
//      INLINED here (bundle:true) so the single .mjs has no sibling import (which would not
//      resolve in the snippet dir).
//
//   2. entry.ts -> entry.mjs
//      The wrangler `main`. The wrangler-special imports (engine.wasm CompiledWasm,
//      stdlib.bundle.txt Text, build/worker/shim.mjs) are kept EXTERNAL so wrangler/worker-build
//      resolve them at the wrangler-bundle step. engine-hash.js is ALSO external — it is
//      regenerated by engine-hash.mjs AFTER this step, so inlining it would freeze a stale hash;
//      wrangler bundles the FRESH file at deploy. stdlib-meta is inlined (pure data, stable).
//
// Determinism: format=esm, no minify, target matches tsconfig (ES2022). Behavior identical.

import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

const COMMON = {
  bundle: true,
  format: "esm",
  target: "es2022",
  platform: "neutral",
  // ts-blank-space (bundled into kernel-glue) imports "typescript" for its scanner/parser; the
  // "neutral" platform ignores package "main" by default, so name the fields explicitly to resolve
  // the CJS entry. Bundling pulls the TS parser into the single .mjs (host-side only).
  mainFields: ["module", "main"],
  minify: false,
  sourcemap: false,
  legalComments: "none",
};

// 1. kernel-glue: self-contained single-file ESM (repl-transform + ts-blank-space inlined).
// ts-blank-space pulls in the "typescript" parser, which `require(...)`s Node built-ins both
// EAGERLY at module top-level AND via computed `require(name)` env probing (os.platform() at
// init). The wasm-bindgen snippet that worker-build re-bundles MUST be fully self-contained — it
// re-runs esbuild with NO externals and a browser platform, so we can neither leave `import"fs"`
// nor reference `node:*`. Instead, alias every bare builtin to a tiny self-contained functional
// shim module AND inject a banner `require()` (intercepting static + computed requires) that
// resolves to that same shim. The shim is behavior-correct ONLY for the env-probe surface TS
// touches at init (os.platform, path.*, process.*); the in-memory scanner/createSourceFile path
// ts-blank-space uses performs no real fs/process I/O, so the shim is never functionally relied
// on beyond init. Host-side only; the VM heap never sees any of this.
const NODE_SHIM = resolve(here, "node-builtin-shim.mjs");
const NODE_BUILTINS = ["fs", "path", "os", "inspector", "crypto", "perf_hooks", "module", "url",
  "buffer", "util", "child_process", "readline", "tty", "v8", "vm", "events", "stream",
  "string_decoder", "assert", "process", "net", "http", "https", "zlib", "worker_threads"];
const NODE_ALIAS = Object.fromEntries(
  NODE_BUILTINS.flatMap((m) => [[m, NODE_SHIM], ["node:" + m, NODE_SHIM]])
);
const REQUIRE_BANNER =
  `import __NODE_SHIM from ${JSON.stringify(NODE_SHIM)};` +
  "const require=(n)=>__NODE_SHIM;" +
  // CJS globals the bundled typescript reads at init under ESM output (esbuild does not inject
  // these for format:esm). Harmless constants; the scanner path never uses them meaningfully.
  'const __filename="/kernel-glue.mjs";const __dirname="/";';
await build({
  ...COMMON,
  entryPoints: [resolve(root, "src/kernel-glue.ts")],
  outfile: resolve(root, "src/kernel-glue.mjs"),
  alias: NODE_ALIAS,
  banner: { js: REQUIRE_BANNER },
});
console.log("[build-ts] src/kernel-glue.ts -> src/kernel-glue.mjs");

// 2. entry: keep the wrangler-special imports external (resolved by wrangler rules / worker-build).
await build({
  ...COMMON,
  entryPoints: [resolve(root, "entry.ts")],
  outfile: resolve(root, "entry.mjs"),
  external: ["*.wasm", "*.txt", "./build/worker/shim.mjs", "./src/engine-hash.js"],
});
console.log("[build-ts] entry.ts -> entry.mjs");
