// SHA-256 the engine wasm into src/engine-hash.js (the engine identity / restore guard).
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const wasm = resolve(root, "src/engine.wasm");
const h = createHash("sha256").update(readFileSync(wasm)).digest("hex").slice(0, 32);
writeFileSync(
  resolve(root, "src/engine-hash.js"),
  `// AUTO-GENERATED by scripts/engine-hash.mjs — do not edit.\nexport const ENGINE_HASH = ${JSON.stringify("rust-" + h)};\n`
);
console.log("[engine-hash] ENGINE_HASH = rust-" + h);
