// Build-time engine content-hash bake-in (EXP-9 retired the runtime double-import).
//
// EXP-9 imported quickjs.wasm twice (CompiledWasm + Data bytes) just to SHA-256 it
// at runtime. CompiledWasm modules cannot be hashed at runtime on workerd, so we
// hash the wasm bytes HERE at build time and write the hex into src/engine-hash.js,
// which the JS glue imports as a constant. One import, no runtime hashing.
import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const wasmPath = join(__dirname, "..", "src", "quickjs.wasm");
const outPath = join(__dirname, "..", "src", "engine-hash.js");

const bytes = await readFile(wasmPath);
const hash = createHash("sha256").update(bytes).digest("hex");

await writeFile(
  outPath,
  `// AUTO-GENERATED by scripts/engine-hash.mjs at build time. Do not edit.\n` +
    `// SHA-256 of src/quickjs.wasm — the interpreter "engine version" identity.\n` +
    `export const ENGINE_HASH = ${JSON.stringify(hash)};\n`,
);
console.log(`[engine-hash] quickjs.wasm sha256 = ${hash} (${bytes.length} bytes)`);
