// Bake the dynamic-facet sources + wasm bytes into a generated src/modules.gen.js
// that the supervisor imports. Worker Loader `modules` values are strings (js) or
// ArrayBuffers (data). We ship JS as a `text`-imported string and wasm as base64 we
// decode to ArrayBuffer at supervisor runtime (the supervisor is a normal Worker, so
// it can base64-decode; the FACET receives a real {data:ArrayBuffer} module).
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, "..", "src");

// tiny.wasm = 41-byte hand-built `(func (export "add") (i32 i32) -> i32)` module
// (regenerated here so it need not be committed as a binary).
const TINY = Uint8Array.from([
  0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x07, 0x01, 0x60, 0x02,
  0x7f, 0x7f, 0x01, 0x7f, 0x03, 0x02, 0x01, 0x00, 0x07, 0x07, 0x01, 0x03, 0x61,
  0x64, 0x64, 0x00, 0x00, 0x0a, 0x09, 0x01, 0x07, 0x00, 0x20, 0x00, 0x20, 0x01,
  0x6a, 0x0b,
]);
if (!existsSync(join(src, "tiny.wasm"))) writeFileSync(join(src, "tiny.wasm"), TINY);

const counter = readFileSync(join(src, "facet-counter.js"), "utf8");
const wasmProbe = readFileSync(join(src, "facet-wasmprobe.js"), "utf8");
const tinyWasmB64 = Buffer.from(TINY).toString("base64");

// quickjs.wasm is large (~1.6MB). Bake it ONLY if present (kernel-facet attempt).
// quickjs.wasm: prefer a local copy under src/, else source it from v0.2.
let quickjsB64 = "";
for (const cand of [join(src, "quickjs.wasm"), join(src, "..", "..", "v0.2", "src", "quickjs.wasm")]) {
  try {
    quickjsB64 = readFileSync(cand).toString("base64");
    break;
  } catch {}
}
let kernelGlue = "";
try {
  kernelGlue = readFileSync(join(src, "facet-kernel.js"), "utf8");
} catch {}

// quickjs-wasi dist files (self-contained ESM, 4 files importing each other).
let qjsDist = {};
try {
  const dist = join(here, "..", "..", "v0.2", "node_modules", "quickjs-wasi", "dist");
  for (const f of ["index.js", "wasi-shim.js", "extensions.js", "version.js"]) {
    qjsDist[f] = readFileSync(join(dist, f), "utf8");
  }
} catch (e) {
  console.warn("quickjs-wasi dist not found:", e.message);
}

const out = `// GENERATED by scripts/bake-modules.mjs — do not edit.
export const COUNTER_SRC = ${JSON.stringify(counter)};
export const WASMPROBE_SRC = ${JSON.stringify(wasmProbe)};
export const TINY_WASM_B64 = ${JSON.stringify(tinyWasmB64)};
export const QUICKJS_WASM_B64 = ${JSON.stringify(quickjsB64)};
export const KERNEL_GLUE_SRC = ${JSON.stringify(kernelGlue)};
export const QJS_DIST = ${JSON.stringify(qjsDist)};
`;
writeFileSync(join(src, "modules.gen.js"), out);
console.log(
  `baked modules.gen.js: counter=${counter.length}b wasmProbe=${wasmProbe.length}b tinyWasm=${tinyWasmB64.length}b64 quickjs=${quickjsB64.length}b64 kernelGlue=${kernelGlue.length}b`
);
