// TRACK B — bake the RUST kernel into the supervisor as Worker-Loader facet modules.
//
// THE CONVERGENCE: the live engram-kernel is now Rust (apps/kernel: a Rust DO compiled
// to wasm32-unknown-unknown via wasm-bindgen/worker-build = build/index.js + build/index_bg.wasm,
// PLUS the rquickjs engine.wasm = src/engine.wasm). The JS-kernel cloud baked glue.js + a JS
// facet DO class. Here we instead deliver the Rust DO class into the facet.
//
// KEY FEASIBILITY FACTS (verified against apps/kernel/build/index.js):
//   - index.js (the wasm-bindgen glue) is plain JS and EXPORTS `KernelDO` (the DO class) and a
//     default WorkerEntrypoint. It can be a Worker-Loader {js} module.
//   - It instantiates BOTH wasm via `new WebAssembly.Instance(Module, imports)` — i.e. from a
//     PRECOMPILED WebAssembly.Module, NOT raw bytes. Raw-bytes WebAssembly.compile is blocked in
//     a facet; instantiating a precompiled Module is NOT. So both wasm ship as {wasm} modules.
//       * index_bg.wasm (the Rust DO bg-wasm) is `import Dt from "./index_bg.wasm"` inside index.js
//         -> ship as a {wasm} module at the SAME relative path.
//       * engine.wasm (rquickjs) is read via `globalThis.__ENGINE_MODULE` (a lazy getter) -> the
//         facet main sets that global to the {wasm}-imported Module before any kernel op.
//   - index.js reads 4 globals: __ENGINE_MODULE, __ENGINE_HASH, __STDLIB_BUNDLE, __STDLIB_META.
//
// So the facet MAIN module is a tiny JS shim (facet-rust.js) that imports engine.wasm as {wasm},
// the stdlib text/meta, sets the 4 globals, and re-exports KernelDO from index.js. The supervisor
// loads `facet-rust.js` as mainModule and `getDurableObjectClass("KernelDO")`.
import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const src = join(root, "src");
const kernelRust = join(root, "..", "..", "apps", "kernel");

// The Rust DO wasm-bindgen glue + its bg-wasm (worker-build output).
const indexJs = readFileSync(join(kernelRust, "build", "index.js"), "utf8");
const indexBgWasm = readFileSync(join(kernelRust, "build", "index_bg.wasm"));
// The rquickjs engine wasm + its build-time hash.
const engineWasm = readFileSync(join(kernelRust, "src", "engine.wasm"));
let engineHashJs = readFileSync(join(kernelRust, "src", "engine-hash.js"), "utf8");
// engine-hash.js exports `ENGINE_HASH`; we want the raw value baked as a global string.
const engineHashMatch = engineHashJs.match(/ENGINE_HASH\s*=\s*["']([^"']+)["']/);
const engineHash = engineHashMatch ? engineHashMatch[1] : "unknown";

// stdlib bundle + meta (the Rust kernel ships these too; the cloud reuses the cloud copies).
const stdlibBundleTxt = readFileSync(join(src, "stdlib.bundle.txt"), "utf8");
let stdlibMeta;
try {
  stdlibMeta = readFileSync(join(kernelRust, "src", "stdlib-meta.js"), "utf8");
  // kernel ships stdlib-meta.js as an ESM exporting STDLIB_META; make it set the global.
  const m = stdlibMeta.match(/STDLIB_META\s*=\s*([\s\S]*?);?\s*export/);
  if (m) stdlibMeta = `globalThis.__STDLIB_META = ${m[1]};\n`;
} catch (_) {
  stdlibMeta = "globalThis.__STDLIB_META = {};\n";
}

const indexBgB64 = indexBgWasm.toString("base64");
const engineB64 = engineWasm.toString("base64");

// content hash -> codeId (any kernel change => fresh isolate, no stale-codeId foot-gun).
const h = createHash("sha256");
h.update(indexJs);
h.update(indexBgWasm);
h.update(engineWasm);
h.update(stdlibBundleTxt);
h.update(engineHash);
const hash = h.digest("hex").slice(0, 16);
const codeId = "rustkernel-" + hash;

// The facet MAIN module: set globals from {wasm}/{text}/{js} loader modules, re-export KernelDO.
const facetMain = `// GENERATED — Rust-kernel facet main (mainModule). Sets the 4 globals the Rust DO
// wasm-bindgen glue (index.js) reads, then re-exports the KernelDO durable-object class.
import ENGINE_MODULE from "./engine.wasm";           // {wasm} => precompiled WebAssembly.Module
import STDLIB_BUNDLE_TXT from "./stdlib.bundle.txt";  // {text} => string
import "./stdlib-meta.js";                            // {js}   => sets globalThis.__STDLIB_META
globalThis.__ENGINE_MODULE = ENGINE_MODULE;
globalThis.__ENGINE_HASH = ${JSON.stringify(engineHash)};
globalThis.__STDLIB_BUNDLE = STDLIB_BUNDLE_TXT;
// index.js itself does \`import Dt from "./index_bg.wasm"\` and instantiates it via
// new WebAssembly.Instance(Dt, ...) — Dt arrives as a {wasm} loader module (precompiled).
export { KernelDO } from "./index.js";
export { default } from "./index.js";
`;

const out = `// GENERATED by scripts/bake-rust.mjs — do not edit. TRACK B (Rust kernel as facet).
export const FACET_MAIN_SRC = ${JSON.stringify(facetMain)};
export const KERNEL_INDEX_JS = ${JSON.stringify(indexJs)};
export const INDEX_BG_WASM_B64 = ${JSON.stringify(indexBgB64)};
export const ENGINE_WASM_B64 = ${JSON.stringify(engineB64)};
export const STDLIB_BUNDLE_TXT = ${JSON.stringify(stdlibBundleTxt)};
export const STDLIB_META_SRC = ${JSON.stringify(stdlibMeta)};
export const KERNEL_CODE_ID = ${JSON.stringify(codeId)};
export const ENGINE_HASH = ${JSON.stringify(engineHash)};
`;
writeFileSync(join(src, "modules.rust.gen.js"), out);
console.log(
  `baked RUST kernel facet: index.js=${indexJs.length}b index_bg.wasm=${indexBgWasm.length}B ` +
    `engine.wasm=${engineWasm.length}B stdlib=${stdlibBundleTxt.length}b ` +
    `codeId=${codeId} engineHash=${engineHash}`,
);
