// Bake the V1.1 kernel-facet module set into src/modules.gen.js for the supervisor.
//
// V1.1 adds (over V1.0): the configurable in-VM stdlib bundle + the 5 Tier-0 native
// extension WASM modules, delivered INTO the facet via the Worker-Loader modules map.
// The facet has NO entry.mjs (a dynamically-loaded DO), so the bundle/meta/extension
// registry are set on globalThis inside facet-kernel.js from imported loader modules:
//   - stdlib.bundle.txt   shipped as a {text} module   -> globalThis.__STDLIB_BUNDLE
//   - stdlib-meta.js      shipped as a {js}  module     -> globalThis.__STDLIB_META
//   - ext/<name>.wasm     shipped as {wasm} modules     -> globalThis.__QJS_EXT_MODULES
//     ({wasm} is the ONLY in-facet wasm-delivery path; raw-bytes compile is blocked.)
//
// Produces (exported to the supervisor):
//   - KERNEL_FACET_SRC / KERNEL_GLUE_SRC  : facet + glue source (engine-hash substituted).
//   - QUICKJS_WASM_B64                    : quickjs.wasm bytes (base64) -> {wasm} module.
//   - QJS_DIST                            : quickjs-wasi dist files ({js} under qjs/).
//   - STDLIB_BUNDLE_TXT / STDLIB_META_SRC : stdlib bundle string + meta {js} module source.
//   - EXT_WASM_B64                        : { name: base64 } for the 5 extension .wasm.
//   - KERNEL_CODE_ID / ENGINE_HASH        : sha256(glue+facet+wasm+dist+stdlib+ext, ORDERED).
//
// The engine hash folds in the stdlib bundle AND the 5 extension Module bytes IN ORDER, so
// any change to the libs or extensions yields a new codeId (fresh compile, no stale isolate)
// AND a clean EngineHashMismatchError on a stale snapshot instead of a corrupt restore.
import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const src = join(root, "src");
const vendor = join(root, "vendor");

// glue.js: SINGLE SOURCE OF TRUTH is apps/kernel/src/glue.js (the v0.9.3 kernel glue:
// NativeAllocLimitError OOM backstop, host.subLM, host.ctx, RLM journal replay). The cloud
// no longer keeps its own fork — the deny-default fetch divergence is expressed via the
// `denyFetchByDefault` config flag (forced on per-tenant in facet-kernel.js), so one glue
// serves both apps. We read the kernel's on-disk file (kept canonical for wasm-bindgen's
// `#[wasm_bindgen(module = "/src/glue.js")]`, which needs a real path) and rewrite the bare
// quickjs-wasi import to the in-facet vendored dist (cloud ships no quickjs-wasi dep).
const kernelGluePath = join(root, "..", "kernel", "src", "glue.js");
let glue = readFileSync(kernelGluePath, "utf8");
glue = glue.replace(/from\s+["']quickjs-wasi["']/g, 'from "./qjs/index.js"');

let facet = readFileSync(join(src, "facet-kernel.js"), "utf8");

const wasmBytes = readFileSync(join(vendor, "quickjs.wasm"));
const wasmB64 = wasmBytes.toString("base64");

// quickjs-wasi dist (self-contained ESM). Vendored copy (byte-identical to v0.2/v1).
const qjsDist = {};
for (const f of ["index.js", "wasi-shim.js", "extensions.js", "version.js"]) {
  qjsDist[f] = readFileSync(join(vendor, "qjs-dist", f), "utf8");
}

// V1.1 stdlib: the esbuilt bundle (JSON string) + meta. build-stdlib.mjs writes these.
const stdlibBundleTxt = readFileSync(join(src, "stdlib.bundle.txt"), "utf8");
const stdlibMeta = readFileSync(join(src, "stdlib-meta.json"), "utf8");
// stdlib-meta is delivered as a {js} module that sets the global (parsing happens once).
const stdlibMetaSrc = `globalThis.__STDLIB_META = ${stdlibMeta};\n`;

// V1.1 extensions: 5 prebuilt quickjs-wasi .so (renamed .wasm, bytes unchanged) in ORDER.
const EXTENSION_ORDER = ["crypto", "encoding", "url", "structured-clone", "headers"];
const extBytes = {};
const extB64 = {};
for (const name of EXTENSION_ORDER) {
  const b = readFileSync(join(vendor, "ext", `${name}.wasm`));
  extBytes[name] = b;
  extB64[name] = b.toString("base64");
}

// Content hash over EVERYTHING that defines the kernel isolate, in a fixed order:
// glue, facet (pre-substitution), quickjs.wasm, qjs dist (sorted), stdlib bundle,
// then the 5 extension Module bytes IN EXTENSION_ORDER (order-sensitive).
const h = createHash("sha256");
h.update(glue);
h.update(facet.replace("__ENGINE_HASH__", ""));
h.update(wasmBytes);
for (const f of Object.keys(qjsDist).sort()) h.update(qjsDist[f]);
h.update(stdlibBundleTxt);
for (const name of EXTENSION_ORDER) h.update(extBytes[name]); // ordered, NOT sorted
const hash = h.digest("hex").slice(0, 16);
const codeId = "kernel-" + hash;
const engineHash = "v11-" + hash;

facet = facet.replace("__ENGINE_HASH__", engineHash);

const out = `// GENERATED by scripts/bake-modules.mjs — do not edit.
export const KERNEL_GLUE_SRC = ${JSON.stringify(glue)};
export const KERNEL_FACET_SRC = ${JSON.stringify(facet)};
export const QUICKJS_WASM_B64 = ${JSON.stringify(wasmB64)};
export const QJS_DIST = ${JSON.stringify(qjsDist)};
export const STDLIB_BUNDLE_TXT = ${JSON.stringify(stdlibBundleTxt)};
export const STDLIB_META_SRC = ${JSON.stringify(stdlibMetaSrc)};
export const EXT_WASM_B64 = ${JSON.stringify(extB64)};
export const EXTENSION_ORDER = ${JSON.stringify(EXTENSION_ORDER)};
export const KERNEL_CODE_ID = ${JSON.stringify(codeId)};
export const ENGINE_HASH = ${JSON.stringify(engineHash)};
`;
writeFileSync(join(src, "modules.gen.js"), out);
const extTotal = EXTENSION_ORDER.reduce((a, n) => a + extBytes[n].length, 0);
console.log(
  `baked: glue=${glue.length}b facet=${facet.length}b wasm=${wasmBytes.length}B ` +
    `qjsDist=${Object.keys(qjsDist).length}files stdlib=${stdlibBundleTxt.length}b ` +
    `ext=${EXTENSION_ORDER.length}mods/${extTotal}B codeId=${codeId} engineHash=${engineHash}`,
);
