import WebSocket from "ws";
const BASE = "wss://montydyn-v06.umg-bhalla88.workers.dev";
const sleep = ms => new Promise(r=>setTimeout(r,ms));
function connect(id){
  const ws = new WebSocket(`${BASE}/ws?id=${encodeURIComponent(id)}`);
  const pending=[]; let onMsg=null;
  ws.on("message", d=>{const m=JSON.parse(d.toString()); if(onMsg){const cb=onMsg;onMsg=null;cb(m);}else pending.push(m);});
  const ready=new Promise((res,rej)=>{ws.on("open",res);ws.on("error",rej);});
  const send=obj=>new Promise(res=>{if(pending.length)return res(pending.shift());onMsg=res;ws.send(JSON.stringify(obj));});
  return {ws,ready,send,close:()=>ws.close()};
}
const sid = "v06-stdlib-"+Date.now();
const c = connect(sid); await c.ready;
const cr = await c.send({t:"create", config:{modules:true}});
console.log("CREATE stdlib loaded:", JSON.stringify(cr.stdlib?.loaded), "available:", JSON.stringify(cr.stdlib?.available));
const g0 = await c.send({t:"gen"});
const lo = await c.send({t:"eval", src:"JSON.stringify(_.chunk([1,2,3,4,5],2))"});
console.log("eval _.chunk:", lo.value);
const dj = await c.send({t:"eval", src:"dayjs('2020-06-15T00:00:00Z').format('YYYY-MM-DD')"});
console.log("eval dayjs:", dj.value);
const na = await c.send({t:"eval", src:"nanoid().length"});
console.log("eval nanoid().length:", na.value);
const uu = await c.send({t:"eval", src:"uuid.validate(uuid.v4())"});
console.log("eval uuid valid:", uu.value);
const zd = await c.send({t:"eval", src:"z.object({n:z.number()}).safeParse({n:7}).success"});
console.log("eval zod:", zd.value);
await c.send({t:"eval", src:"globalThis.userState = _.sum([100,200,300])"});
// FORCE in-memory drop then cold real eviction
console.log("evict:", JSON.stringify(await c.send({t:"evict"})));
c.close();
console.log("=== idle 75s for real hibernation ===");
await sleep(75000);
const c2 = connect(sid); await c2.ready;
const g1 = await c2.send({t:"gen"});
console.log(`gen ${g0.generation} -> ${g1.generation} inMemory=${g1.inMemory} reconstructed=${g1.generation>g0.generation}`);
const r_lo = await c2.send({t:"eval", src:"JSON.stringify(_.chunk([9,8,7,6],2))"});
const r_dj = await c2.send({t:"eval", src:"dayjs('2021-01-01T00:00:00Z').format('YYYY')"});
const r_na = await c2.send({t:"eval", src:"typeof nanoid==='function' ? nanoid().length : 'GONE'"});
const r_uu = await c2.send({t:"eval", src:"uuid.validate(uuid.v4())"});
const r_zd = await c2.send({t:"eval", src:"z.string().safeParse('hello').success"});
const r_us = await c2.send({t:"eval", src:"userState"});
const cr2 = await c2.send({t:"create", config:{modules:true}});
console.log("AFTER COLD RESTORE:");
console.log("  restoreSource:", r_lo.restoreSource);
console.log("  _.chunk:", r_lo.value, "| dayjs:", r_dj.value, "| nanoid len:", r_na.value, "| uuid:", r_uu.value, "| zod:", r_zd.value, "| userState:", r_us.value);
console.log("  stdlib.loaded after restore (should be []):", JSON.stringify(cr2.stdlib?.loaded));
const conds={lo:r_lo.value==="[[9,8],[7,6]]",dj:r_dj.value==="2021",na:r_na.value===21,uu:String(r_uu.value)==="true",zd:String(r_zd.value)==="true",us:r_us.value===600,gen:g1.generation>g0.generation,reinject:(cr2.stdlib?.loaded||[]).length===0};
console.log("CONDS:",JSON.stringify(conds));
const pass=Object.values(conds).every(Boolean);
console.log(pass ? ">>> SMOKE PASS: stdlib survived cold restore via snapshot, NO re-inject" : ">>> SMOKE FAIL");
c2.close();
process.exit(pass?0:1);
